// <auto-generated />
namespace Cs20483_Exercicio.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CreateTablesPessoas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateTablesPessoas));
        
        string IMigrationMetadata.Id
        {
            get { return "202002222021244_CreateTablesPessoas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
